#:schema ./config.schema.json
userAgent = "posterboy/0.0.1"

[[sources]]
slug = "kollitsch"
type = "feed"
url = "https://kollitsch.dev/rss.xml"
name = "KOLLITSCH.dev*"

[[sources]]
slug = "hugomodules"
type = "github"
repo = "davidsneighbour/hugo-modules"
name = "GoHugo Modules"

[[targets]]
slug = "discord"
type = "discord"
name = "Discord Update Channel"
hook = ""
template = '''
New post on {{ .source.name }}:
{{ .title }}
{{ .url }}
'''

[[targets]]
slug = "mastodon"
type = "mastodon"
name = "Mastodon"
username = ""
template = '''
New post on {{ .source.name }}:
{{ .title }}
{{ .url }}
'''
